/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management_system;

import Classes.Guest;
import java.util.ArrayList;

/**
 *
 * @author Uzair
 */
public class Admin_Selection extends javax.swing.JFrame {
  ArrayList<Guest> guest = new ArrayList<Guest>();
    /**
     * Creates new form Admin_Selection
     */
    public Admin_Selection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        admin_managestaff = new javax.swing.JButton();
        admin_selection_guest = new javax.swing.JButton();
        admin_selection_canteen = new javax.swing.JButton();
        admin_selection_room = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Selector");

        admin_managestaff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admin_managestaff.setForeground(new java.awt.Color(24, 44, 97));
        admin_managestaff.setText("Manage Staff");
        admin_managestaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_managestaffActionPerformed(evt);
            }
        });

        admin_selection_guest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admin_selection_guest.setForeground(new java.awt.Color(24, 44, 97));
        admin_selection_guest.setText("Manage Guest");
        admin_selection_guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_selection_guestActionPerformed(evt);
            }
        });

        admin_selection_canteen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admin_selection_canteen.setForeground(new java.awt.Color(24, 44, 97));
        admin_selection_canteen.setText("Canteen");
        admin_selection_canteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_selection_canteenActionPerformed(evt);
            }
        });

        admin_selection_room.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admin_selection_room.setForeground(new java.awt.Color(24, 44, 97));
        admin_selection_room.setText("Manage Room");
        admin_selection_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_selection_roomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(admin_selection_guest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_managestaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_selection_canteen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_selection_room, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(admin_managestaff, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(admin_selection_guest, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(admin_selection_canteen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(admin_selection_room, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_managestaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_managestaffActionPerformed
           Manage_Staff managestaff = new Manage_Staff();
           managestaff.show();
// TODO add your handling code here:
    }//GEN-LAST:event_admin_managestaffActionPerformed

    private void admin_selection_guestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_selection_guestActionPerformed
Manage_Guest manageguest = new Manage_Guest(guest);
manageguest.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_selection_guestActionPerformed

    private void admin_selection_canteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_selection_canteenActionPerformed
Canteen canteen = new Canteen(guest);
canteen.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_selection_canteenActionPerformed

    private void admin_selection_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_selection_roomActionPerformed

        Manage_Room manageroom = new Manage_Room();
        manageroom.show();

        // TODO add your handling code here:
    }//GEN-LAST:event_admin_selection_roomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Selection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_managestaff;
    private javax.swing.JButton admin_selection_canteen;
    private javax.swing.JButton admin_selection_guest;
    private javax.swing.JButton admin_selection_room;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
