/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management_system;
import Classes.Room;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Uzair
 */
public class Book_Room extends javax.swing.JFrame {
ArrayList<Room> room;
    /**
     * Creates new form Book_Room
     */
    public Book_Room(ArrayList<Room> room) {
        initComponents();
        this.room = room;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        book_room_roomno = new javax.swing.JTextField();
        book_room_back = new javax.swing.JButton();
        book_room_exit = new javax.swing.JButton();
        book_room = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        book_room_customerno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        book_room_cutomercatagory = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        book_room_cost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Book Room");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Room Number");

        book_room_roomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_room_roomnoActionPerformed(evt);
            }
        });

        book_room_back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        book_room_back.setForeground(new java.awt.Color(24, 44, 97));
        book_room_back.setText("Back");
        book_room_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_room_backActionPerformed(evt);
            }
        });

        book_room_exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        book_room_exit.setForeground(new java.awt.Color(24, 44, 97));
        book_room_exit.setText("Exit");
        book_room_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_room_exitActionPerformed(evt);
            }
        });

        book_room.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        book_room.setForeground(new java.awt.Color(24, 44, 97));
        book_room.setText("Book");
        book_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_roomActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Customer No");

        book_room_customerno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_room_customernoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Customer Catagory");

        book_room_cutomercatagory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_room_cutomercatagoryActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cost");

        book_room_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_room_costActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(79, 79, 79))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(172, 172, 172)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(book_room_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(book_room_customerno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(book_room_roomno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(book_room_cutomercatagory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(book_room_back, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(book_room, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(book_room_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(book_room_roomno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_room_customerno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(book_room_cutomercatagory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(book_room_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_room_back)
                    .addComponent(book_room_exit)
                    .addComponent(book_room))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void book_room_roomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_room_roomnoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_book_room_roomnoActionPerformed

    private void book_room_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_room_backActionPerformed
        Manage_Room manageroom = new Manage_Room();
        manageroom.show();
        this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_book_room_backActionPerformed

    private void book_room_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_room_exitActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_book_room_exitActionPerformed

    private void book_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_roomActionPerformed
Room rooma = new Room();
rooma.setCustomer_no(Integer.parseInt(book_room_customerno.getText()));
rooma.setRoom_no(Integer.parseInt(book_room_roomno.getText()));
rooma.setCatagory(book_room_cutomercatagory.getText().charAt(0));
rooma.setCost(Float.parseFloat(book_room_cost.getText()));
 try
      {
          FileOutputStream fos = new FileOutputStream("room");
          ObjectOutputStream oos = new ObjectOutputStream(fos);
      oos.writeObject(room);
      oos.close();
      fos.close();
      }
      catch(IOException ioe)
      {
        JOptionPane.showMessageDialog(null,"Saving error","Error Message Box",JOptionPane.ERROR_MESSAGE);
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_book_roomActionPerformed

    private void book_room_customernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_room_customernoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_room_customernoActionPerformed

    private void book_room_cutomercatagoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_room_cutomercatagoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_room_cutomercatagoryActionPerformed

    private void book_room_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_room_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_room_costActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Room(Manage_Room.room).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book_room;
    private javax.swing.JButton book_room_back;
    private javax.swing.JTextField book_room_cost;
    private javax.swing.JTextField book_room_customerno;
    private javax.swing.JTextField book_room_cutomercatagory;
    private javax.swing.JButton book_room_exit;
    private javax.swing.JTextField book_room_roomno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
