/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management_system;

import Classes.Room;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Uzair
 */
public class Check_In_Out extends javax.swing.JFrame {
ArrayList<Room> room;
    /**
     * Creates new form Check_In_Out
     */
    public Check_In_Out(ArrayList<Room> room) {
        initComponents();
         this.room = room;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkin = new javax.swing.JRadioButton();
        checkin2 = new javax.swing.JRadioButton();
        check_in_out_back = new javax.swing.JButton();
        check_in_out_back_exit = new javax.swing.JButton();
        check_in_out_save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        check_in_out_roomno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        check_in_out_customerno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkin.setText("Checked In");

        checkin2.setText("Checked Out");

        check_in_out_back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_in_out_back.setForeground(new java.awt.Color(24, 44, 97));
        check_in_out_back.setText("Back");
        check_in_out_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_in_out_backActionPerformed(evt);
            }
        });

        check_in_out_back_exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_in_out_back_exit.setForeground(new java.awt.Color(24, 44, 97));
        check_in_out_back_exit.setText("Exit");
        check_in_out_back_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_in_out_back_exitActionPerformed(evt);
            }
        });

        check_in_out_save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_in_out_save.setForeground(new java.awt.Color(24, 44, 97));
        check_in_out_save.setText("Save");
        check_in_out_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_in_out_saveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Check In & Out");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Room Number");

        check_in_out_roomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_in_out_roomnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Customer Number");

        check_in_out_customerno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_in_out_customernoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(check_in_out_back, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(check_in_out_save, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(check_in_out_back_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkin2)
                            .addComponent(checkin))))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_in_out_customerno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_in_out_roomno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(check_in_out_roomno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(check_in_out_customerno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(checkin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkin2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_in_out_back)
                    .addComponent(check_in_out_back_exit)
                    .addComponent(check_in_out_save))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_in_out_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_in_out_backActionPerformed
        Manage_Room manageroom = new Manage_Room();
        manageroom.show();
        this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_check_in_out_backActionPerformed

    private void check_in_out_back_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_in_out_back_exitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_check_in_out_back_exitActionPerformed

    private void check_in_out_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_in_out_saveActionPerformed
 try {
     FileInputStream fis = new FileInputStream("room");
     ObjectInputStream ois = new ObjectInputStream (fis);
     room = (ArrayList) ois.readObject();
     
 }
 catch(ClassNotFoundException c)
 {
     JOptionPane.showMessageDialog(null,"Class not found","Error Message Box",JOptionPane.ERROR_MESSAGE);
 
 }  catch (FileNotFoundException ex) {
         JOptionPane.showMessageDialog(null,"File not found","Error Message Box",JOptionPane.ERROR_MESSAGE);
    } catch (IOException ex) {
        Logger.getLogger(Check_In_Out.class.getName()).log(Level.SEVERE, null, ex);
    }
 
        // TODO add your handling code here:
    }//GEN-LAST:event_check_in_out_saveActionPerformed

    private void check_in_out_roomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_in_out_roomnoActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_check_in_out_roomnoActionPerformed

    private void check_in_out_customernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_in_out_customernoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_in_out_customernoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check_In_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check_In_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check_In_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check_In_Out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check_In_Out(Manage_Room.room).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check_in_out_back;
    private javax.swing.JButton check_in_out_back_exit;
    private javax.swing.JTextField check_in_out_customerno;
    private javax.swing.JTextField check_in_out_roomno;
    private javax.swing.JButton check_in_out_save;
    private javax.swing.JRadioButton checkin;
    private javax.swing.JRadioButton checkin2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
