/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management_system;
import javax.swing.JOptionPane;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import javafx.scene.control.RadioButton;

/**
 *
 * @author Uzair
 */
public class Login extends javax.swing.JFrame {
String password,username,jradiobutton = "None";
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        login_username = new javax.swing.JTextField();
        username1 = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        login_next = new javax.swing.JButton();
        login_jradiobutton_administrator = new javax.swing.JRadioButton();
        login_jradiobutton_user = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        login_password = new javax.swing.JPasswordField();
        login_next1 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_username.setText("Admin");

        username1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username1.setText("  username");
        username1.setBorder(new javax.swing.border.MatteBorder(null));

        password2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password2.setText("  password");
        password2.setBorder(new javax.swing.border.MatteBorder(null));

        login_next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_next.setForeground(new java.awt.Color(24, 44, 97));
        login_next.setText("Login");
        login_next.setToolTipText("");
        login_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_nextActionPerformed(evt);
            }
        });

        login_jradiobutton_administrator.setSelected(true);
        login_jradiobutton_administrator.setText("Administrator");

        login_jradiobutton_user.setText("User");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 44, 97));
        jLabel1.setText("Hotel Management System");

        login_password.setText("Admin");

        login_next1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_next1.setForeground(new java.awt.Color(24, 44, 97));
        login_next1.setText("Exit");
        login_next1.setToolTipText("");
        login_next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_next1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_password, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(login_username))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(login_next1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_jradiobutton_administrator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(login_jradiobutton_user)
                            .addComponent(login_next, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_password, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(login_jradiobutton_administrator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_jradiobutton_user)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_next1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_nextActionPerformed
// TODO add your handling code here:
{
          // taking username and password
username = login_username.getText();
password = login_password.getText();
            // jradiobutton selection
if (login_jradiobutton_administrator.isSelected())
        {
          jradiobutton = "Admin";      
        }
else if (login_jradiobutton_user.isSelected())
        {
          jradiobutton = "User";
        }
/*else if (login_jradiobutton_administrator.isSelected()&& login_jradiobutton_user.isSelected())
        {
       jradiobutton = "Both";
        }*/
else 
{
jradiobutton = null;
}
// Checking username and passwords
switch (jradiobutton)
{
    // if radio button Admin is Selected
    case "Admin":
    {
        if ("Admin".equals(username) && "Admin".equals(password))
        {
                        Admin_Selection adminselection = new Admin_Selection();
                                  adminselection.show();
                                  this.hide();

        }
        else 
        {
        JOptionPane.showMessageDialog(null,"Wrong username or Password","Error Message Box",JOptionPane.ERROR_MESSAGE);
        }
     
        break;
    }
    // If radiobutton User is Selected
    case "User":
    {
    if ("User".equals(username) && "User".equals(password))
    {
    
    }
    else
    {
        JOptionPane.showMessageDialog(null,"Worng Username or Password","Error Message Box",JOptionPane.ERROR_MESSAGE);
    }
        break;
        }
    //no button is selected
           default:
            {
             JOptionPane.showMessageDialog(null,"Unexpected Error","Error Message Box",JOptionPane.ERROR_MESSAGE); 
            }
              }  


}



    }//GEN-LAST:event_login_nextActionPerformed

    private void login_next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_next1ActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_login_next1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton login_jradiobutton_administrator;
    private javax.swing.JRadioButton login_jradiobutton_user;
    private javax.swing.JButton login_next;
    private javax.swing.JButton login_next1;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JTextField login_username;
    private javax.swing.JLabel password2;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables
}
