/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management_system;
import Classes.Guest;
import java.util.ArrayList;
/**
 *
 * @author Uzair
 */
public class Manage_Guest extends javax.swing.JFrame {
 public static ArrayList<Guest> guest ;
    /**
     * Creates new form Manage_Guest
     */
    public Manage_Guest(ArrayList<Guest> guest) {
        initComponents();
        this.guest = guest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manage_guest_add = new javax.swing.JButton();
        manage_guest_see = new javax.swing.JButton();
        manage_guest_see1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Manage Guest");

        manage_guest_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manage_guest_add.setForeground(new java.awt.Color(24, 44, 97));
        manage_guest_add.setText("Add Guest");
        manage_guest_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_guest_addActionPerformed(evt);
            }
        });

        manage_guest_see.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manage_guest_see.setForeground(new java.awt.Color(24, 44, 97));
        manage_guest_see.setText("See Guest");
        manage_guest_see.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_guest_seeActionPerformed(evt);
            }
        });

        manage_guest_see1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manage_guest_see1.setForeground(new java.awt.Color(24, 44, 97));
        manage_guest_see1.setText("Exit");
        manage_guest_see1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_guest_see1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manage_guest_see1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manage_guest_see, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manage_guest_add, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(manage_guest_add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manage_guest_see, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(manage_guest_see1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manage_guest_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_guest_addActionPerformed
                 Add_Guest addguest = new Add_Guest(guest);
                 addguest.show();
                 // TODO add your handling code here:
    }//GEN-LAST:event_manage_guest_addActionPerformed

    private void manage_guest_seeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_guest_seeActionPerformed
              See_Guest seeguest = new See_Guest();
              seeguest.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_guest_seeActionPerformed

    private void manage_guest_see1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_guest_see1ActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_guest_see1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Guest(guest).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manage_guest_add;
    private javax.swing.JButton manage_guest_see;
    private javax.swing.JButton manage_guest_see1;
    // End of variables declaration//GEN-END:variables
}
